import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from '../components/Header/Header'
import { HeroSection } from '../components/HeroSection/HeroSection'

const Home: NextPage = () => {
  return (
    <div className='m-0 p-0 w-screen'>
      <Head>
        <title>My Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-screen w-screen bg-gray-100'>
        <Header />
        <HeroSection />
      </div>
    </div>
  )
}

export default Home
